### ISSUE TITLE
No se ven los resultados de Carrefour, Coto, Disco y Vea

### ISSUE THREAD

**Issue by matiasbontempo** [matiasbontempo/ratoneando-go#1]

**Comment by yoursweetginger** [comment]
¿Descubriste lo que pasó?

**Comment by facundopadilla** [comment]
Buenas, también estoy creando un scrapper para los sitios que usan VTEX como Carrefour y un par más, hace días que viene fallando o yendo y viniendo y tengo la teoría no confirmada que están bloqueando/modificando los endpoints para el acceso público o migrando a otros endpoints o sacando un V2

Hoy me está pasando con Carrefour (me pasé haciendole ingenieria inversa a la página y parece que están metiendo server-side rendering en ciertas partes), ayer me pasaba con Farmacity (hoy anda joya), con los de Cencosud cero problemas (Jumbo, Vea, Disco no tengo problemas, pero con Blastein y Easy por ahí tienden a fallar).

Capaz es otro error al que se está enfrentando Mati pero lo tiro como dato de color si alguno más está tratando y no puede.

**Comment by dpaul20** [comment]
Por ahora solo logre solucionar la búsqueda en Carrefour actualizando las variables de la query dejo [PR](https://github.com/matiasbontempo/ratoneando-go/pull/3/files)

**Comment by matiasbontempo** [comment]
Genio! Ahora lo reviso! Tenía la sospecha de que se habían roto el hash de nuevo porque ya me había pasado.

**Comment by matiasbontempo** [comment]
> Buenas, también estoy creando un scrapper para los sitios que usan VTEX como Carrefour y un par más, hace días que viene fallando o yendo y viniendo y tengo la teoría no confirmada que están bloqueando/modificando los endpoints para el acceso público o migrando a otros endpoints o sacando un V2
> 
> Hoy me está pasando con Carrefour (me pasé haciendole ingenieria inversa a la página y parece que están metiendo server-side rendering en ciertas partes), ayer me pasaba con Farmacity (hoy anda joya), con los de Cencosud cero problemas (Jumbo, Vea, Disco no tengo problemas, pero con Blastein y Easy por ahí tienden a fallar).
> 
> Capaz es otro error al que se está enfrentando Mati pero lo tiro como dato de color si alguno más está tratando y no puede.

Gracias por el análisis! Es muy probable que estén cambiando cosas. Hace unos meses ya había tenido problemas con hash que se manda en el request y ahora pareciera ser lo mismo nuevamente.

**Comment by facundopadilla** [comment]
Vuelvo a molestar, ¿explotaron de nuevo todos?, pensé que era un tema de IP pero nope.

**Comment by facundopadilla** [comment]
Estuve notando que están dejando de utilizar el "productSearchV3" y directamente están pasando en el payload ésto:

```json
{
  "__bindingId": "...",
  "appsEtag": "remove",  # este antes no se usaba, ahora lo agregaron
  "domain": "store",
  "extensions": "{\"persistedQuery\":{\"version\":1,\"sha256Hash\":\"...\",\"sender\":\"jumboargentinaio.store-theme@4.x\",\"provider\":\"vtex.search-graphql@0.x\"},\"variables\":\"eyJpZCI6IjM1MDI2MSJ9\"}",
  "locale": "es-AR",
  "maxAge": "short",
  "variables": "{}",  # este lo agregaron (ya existia igualmente)
  "workspace": "master"
}
```

Dentro de 'extensions', ahora mandan el sender propio, antes era uno genérico (vtex.store-resources@0.x) y ahora por ejemplo, el de jumbo es: jumboargentinaio.store-theme@4.x

Otra cosa que sigo notando es que se están yendo más al server-side rendering ("parece" que de ahí sacan los ID´s de los productos) y despues le pegan a la API y renderizan contenido.
